# Generated by Django 4.1.5 on 2024-05-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
